
# This is a Terragrunt module generated by boilerplate.
terraform {
  #source = "git::https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example.git//modules/mysql?ref=v0.8.1"
}








# include "root" {
#   path = find_in_parent_folders()
# }

# inputs = {
#   # --------------------------------------------------------------------------------------------------------------------
#   # Required input variables
#   # --------------------------------------------------------------------------------------------------------------------

#   # Description: The name of the DB
#   # Type: string
#   name = "" # TODO: fill in value

#   # Description: The instance class of the DB (e.g. db.t2.micro)
#   # Type: string
#   instance_class = "" # TODO: fill in value

#   # Description: The amount of space, in GB, to allocate for the DB
#   # Type: number
#   allocated_storage = 0 # TODO: fill in value

#   # Description: The type of storage to use for the DB. Must be one of: standard, gp2, or io1.
#   # Type: string
#   storage_type = "" # TODO: fill in value

#   # Description: The username for the master user of the DB
#   # Type: string
#   master_username = "" # TODO: fill in value

#   # Description: The password for the master user of the DB
#   # Type: string
#   master_password = "" # TODO: fill in value


#   # --------------------------------------------------------------------------------------------------------------------
#   # Optional input variables
#   # Uncomment the ones you wish to set
#   # --------------------------------------------------------------------------------------------------------------------

#   # Description: If set to true, skip the final snapshot of the DB when it is being deleted. In production, this should always be false. Only set it to true for automated testing.
#   # Type: bool
#   # skip_final_snapshot = false

#   # Description: The version of MySQL to run. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.Concepts.VersionMgmt.html
#   # Type: string
#   # engine_version = "8.0.36"

# }
